### ISSUE TITLE
.eslintrc file in yaml format?

### ISSUE THREAD

**Issue by BurtHarris** [spicydonuts/eslint-starter#1]
It looks like the **.eslintrc** file is in YAML format (with the leading `---`), but it lacks a `.yaml` or `.yml` extension.

While its not clear what parser should be used if a file lacks an extension, some related projects, e.g. __grun-eslint__ seem to be confused using the format of this sample.

**Comment by BurtHarris** [comment]
Perhaps I've got the root cause wrong.   Here's what I'm seeing:
```
C:\code\eslint-starter>gulp
[10:04:04] Using gulpfile C:\code\eslint-starter\gulpfile.js
[10:04:04] Starting 'lint'...
C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\ignored-paths.js:195
                    throw e;
                    ^

SyntaxError: Unexpected token } in JSON at position 817
    at JSON.parse (<anonymous>)
    at new IgnoredPaths (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\ignored-paths.js:176:55)
    at CLIEngine.isPathIgnored (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\cli-engine.js:702:30)
    at Transform.util.transform [as _transform] (C:\code\eslint-starter\node_modules\gulp-eslint\index.js:31:14)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at Transform.Writable.write (_stream_writable.js:274:11)
    at write (C:\code\eslint-starter\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
```

**Comment by BurtHarris** [comment]
Perhaps I've got the root cause wrong, it may be a problem in **grunt-eslint**, adding the .yml extension didn't seem to fix it.
